version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-228-209-117.eu-west-1.compute.amazonaws.com
            database: dfbhqqtufko0hq
            user: xedcmiezuapbng
            password: 6f686328845bd642c903c34d33cffd678bbc7c98a2bdc43bdd56a07327ac9d3b
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true